batch_size: 100
decision_strategy: prob
envelope_threshold: 1.0e-10
flat_sample: false
flat_width: 1
from_scratch: false
gamma: 0.95
global_seed: 0
learning_strategy: bayes_optimistic
load: null
max_steps: 15
num_samples: 5000
num_skeletons: 100
planner: tampura_policy
print_options: ab,a,o,r
pwa: 0.2
pwk: 3.0
real_camera: false
real_execute: false
save_dir: /home/am/tamp_multi_agent/notebooks/runs/run1748419926.9571824
symk_direction: fw
symk_selection: unordered
symk_simple: true
task: class_uncertain
vis: false
vis_graph: true
