(define (problem generated_0)
  (:domain generated)
  (:objects robot_1 - robot robot_2 - robot region_mug - region region_door - region region_stable_mug - region mug - physical door - door )
  (:init
    (robot robot_1)
    (eq robot_1 robot_1)
    (robot robot_2)
    (eq robot_2 robot_2)
    (region region_mug)
    (eq region_mug region_mug)
    (region region_door)
    (eq region_door region_door)
    (region region_stable_mug)
    (eq region_stable_mug region_stable_mug)
    (physical mug)
    (eq mug mug)
    (door door)
    (eq door door)
    (in_rob robot_1 region_stable_mug)
    (in_obj mug region_mug)
    (in_rob robot_2 region_stable_mug)
    (nothing_action robot_2)
    (stable mug region_mug)
    (stable mug region_stable_mug)
    (is_ego robot_1)
  )
  (:goal (and (exists (?rob - robot) (holding ?rob mug)) (not (open door))))
  (:metric minimize (total-cost))
)